# Generated by Django 5.2.4 on 2025-07-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
