# Generated by Django 5.2.4 on 2025-07-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_delivery_address_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
    ]
